name = "Magic Greg: Arcane Breakthrough"
author = "Ra'Ahm"
version = "ALPHA 1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c281b383180b0d79acd8aa33eb769fbe58fffcfc50bae5c7259d2adb62425fb8"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
