name = "Magic Greg: Arcane Breakthrough"
author = "Ra'Ahm"
version = "ALPHA 1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b2d86affd393d9dc287e9251682dbad89a37a827673ce100fd5b84792357f53"

[versions]
forge = "47.4.6"
minecraft = "1.20.1"
